[tool.poetry]
name = "keiko"
version = "0.1.0"
description = "KAT report engine using LateX to generate PDF"
authors = [""]
license = "EUPL"

[tool.pylint.format]
max-line-length = "120"

[tool.pylint."MESSAGES CONTROL"]
disable = ["R0914","W1514"] # Ignore too-many-local-variables and unspecified encodings
extension-pkg-whitelist = "pydantic" # Ignore pydantic import checks

[tool.black]
line-length = 120
target-version = ['py38']

[tool.mypy]
python_version = "3.8"
strict = true

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
pydantic = "^1.9.2"
Jinja2 = "^3.1.2"
fastapi = "^0.79.1"
uvicorn = "^0.18.2"
vulture = "^2.5"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^5.0.4"
mypy = "^0.971"
pylint = "^2.14.5"
robotframework-tidy = "^3.2"
robotframework = "^5.0.1"
robotframework-debuglibrary = "^2.3.0"
robotframework-requests = "^0.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
