name: Check missing translations
on:
  pull_request:
    branches:
      - "**"
  push:
    tags:
      - v*

jobs:
  locale:
    strategy:
      matrix:
        locale: ['nl', 'pap']

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Install gettext
        run: sudo apt-get -f install gettext

      - name: Run msgfmt and check for untranslated ${{ matrix.locale }}
        run: msgcmp locale/${{ matrix.locale }}/LC_MESSAGES/django.po locale/${{ matrix.locale }}/LC_MESSAGES/django.po
