name: Run the test suite


on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'develop'
      - 'master'

jobs:
  Tests:

    runs-on: ubuntu-20.04
    env:
      COMPOSE_FILE: .ci/docker-compose.yml

    steps:
      - uses: actions/checkout@v1

      - name: Configure git
        env:
          TOKEN: ${{ secrets.RDO_REPO_RO }}
        run: git config --global url."https://${{ secrets.RDO_REPO_RO }}@github.com/".insteadOf "ssh://git@github.com/"

      - name: Install pip
        run: python3.8 -m pip install --upgrade pip

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Install requirements
        run: find . -name requirements.txt | xargs -L 1 pip install -r

      - name: Run pytests
        run: python3.8 -m pytest
